### ISSUE TITLE
Streak Incorrectly Updated

### ISSUE THREAD

**Issue by kmanjt** [DenverCoder1/github-readme-streak-stats#475]
**Describe the bug**
My streak has reset to 1 day despite it being continued to 91 days

**To Reproduce**

1. My streak (https://streak-stats.demolab.com/?user=kmanjt) is showing 1 day despite it being 91 days

**Expected behavior**
91 day streak should be shown instead of 1 - I have tested using a different endpoint with more customisations, which also showed the same.

**Screenshots**
![image](https://user-images.githubusercontent.com/95762894/226298357-3b6eaead-62bd-44d4-83c9-4fad009dcb6e.png)
![image](https://user-images.githubusercontent.com/95762894/226298432-6decb27d-14b5-4d35-8d23-493ab073565e.png)

**Desktop (please complete the following information):**

- OS: Windows 11
- Browser Chrome

**Smartphone (please complete the following information):**

- Device: OnePlus 7T 
- OS: Android
- Browser: Chrome

**Additional context**
This has not happened before.

**Comment by DenverCoder1** [comment]
The GitHub API shows that you have no contributions on March 19

![image](https://user-images.githubusercontent.com/20955511/226300848-fbc5d161-cc8a-46ec-bac1-d3051ac7b232.png)

Please see the relevant FAQ section for ways to fix it

https://github.com/DenverCoder1/github-readme-streak-stats/blob/main/docs/faq.md#why-doesnt-my-streak-stats-match-my-contribution-graph

**Comment by kmanjt** [comment]
Hi @DenverCoder1 thank you for the speedy response - I am confused, this is not a time zone issue - there is a public contribution on that date.

**Comment by DenverCoder1** [comment]
It doesn't matter what the contribution graph shows. As I have pointed out, it shows differently when I view your profile.

What matters is what the GitHub GraphQL API returns and it shows similar to the chart I see that are no contributions on March 19. This means either the contribution is not public or the contribution is being counted for a different day on the API due to a timezone difference (the GitHub GraphQL API returns contributions for a timezone other than your local timezone).

**Comment by kmanjt** [comment]
Hi @DenverCoder1 okay thank you for the clarification. I have added new commits to a repository for midday on the 19th - my graph is still only showing the 1 contribution for that day however - could you please verify if the issue is now resolved?

**Comment by DenverCoder1** [comment]
The API is still showing 0 contributions (two on March 18, none on March 19, two on March 20)

```
{
    "contributionDays": [
        {
            "contributionCount": 0,
            "date": "2023-03-19"
        },
        {
            "contributionCount": 2,
            "date": "2023-03-20"
        }
    ]
},
```

**Comment by kmanjt** [comment]
@DenverCoder1 thank you, I have followed all of the options outlined in the FAQ to resolve this and all of the changes are still showing as coming from today instead of the 19th. 

GIT_COMMITTER_DATE="2022-03-19T14:30:00+00:00" git commit --amend --no-edit --date "2022-03-19T12:30:00+00:00" --allow-empty 

git push --force

and 

git commit --date="2022-08-02 12:00" -m "Test commit" --allow-empty
git push

**Comment by kmanjt** [comment]
Update streak has returned - perhaps FAQ should include the following as none of the other options worked for me:
```bash
git commit --date="1 day ago" -m "test" --allow-empty 
git push
```
